### ISSUE TITLE
PHP errors with OCS 2.5

### ISSUE THREAD

**Issue by Bevito** [OCSInventory-NG/OCSInventory-ocsreports#535]
### General informations
Operating system : 

### Server installation method ( Only one choice )
- [ ] RPM Package
- [ X] Install SH
- [ ] Manual installation

### Server informations
Debian Stretch 9.5
Php version : PHP 7.0.30-0+deb9u1
Mysql / Mariadb / Percona version : 10.1.26-0+deb9u1
Apache version : 2.4.25-3+deb9u5

### OCS Inventory informations
Ocsreports version : 2.5

### Problem's description
Hi, 

I did note see this bug in the issues, so I let you know.
The problem was already report here : https://ask.ocsinventory-ng.org/9864/upgrade-to-2-5-some-info-from-activity-no-list

On welcome page, we can find theses PHP errors in apache2 log : 
- PHP Warning:  vsprintf(): Too few arguments in /usr/share/ocsinventory-reports/ocsreports/require/function_commun.php on line 74, referer: https://xxxx.xxx/ocsreports/
- PHP Warning:  mysqli_query(): Empty query in /usr/share/ocsinventory-reports/ocsreports/require/function_commun.php on line 103, referer: https://xxxx.xxx/ocsreports/

If we click on "Machines contacted today" for example, we obtained all the machine in the inventory, not the "machines contacted today".

Thanks a lot for your help.

Best regards.

**Comment by maaguiar** [comment]
I have a same problem after update to 2.5

**Comment by tomJa99** [comment]
I've got the same problem as well after updating my OCS Inventory NG Server from 2.4 to 2.5.

I use PHP 5.6, MySQL 5.1.73 and Perl 5.10.1 on my Apache 2 Webserver.

In additon to these problems, my Serverlog File reported this error as well:

PHP Fatal Error: Can't use method return value in write context in /usr/share/ocsinventory-reports/ocsreports/require/search/TranslationSearch.php on line 224, referer http://10.220.167.250/ocsreports/index.php?function=search_soft

The last error might not be connected to the warning mentioned at this page, but nevertheless it is there.

**Comment by maaguiar** [comment]
Problem solved!!! Thank you!!!

But when language not english, no result it show:

URL when language **_is english_**:

https://ocsinventory-ng/ocsreports/index.php?function=visu_search&fields=HARDWARE-LASTCOME&comp=small&values=08/01/2018%2012:00&values2=&type_field=

URL when language **_not is english_**: (dont include hour)

https://ocsinventory-ng.labfranceschi.com.br/ocsreports/index.php?function=visu_search&fields=HARDWARE-LASTCOME&comp=small&values=01/08/2018&values2=&type_field=

**Comment by charleneauger** [comment]
Hi @,

This bug has been fix with PR #563 

Regards,
Charlene Auger
